[package]
name = "nfs-mamont"
version = "0.0.0"
edition = "2021"
authors = ["Rmamonts"]
description = "A Rust NFS Server implementation"
publish = false
rust-version = "1.83.0"

[lib]
doctest = false

[dependencies]
async-trait = "0.1.89"
nix = { version = "0.30.1", features = ["feature", "fs"] }
tokio = { version = "1.47", features = ["full", "time"] }

[dev-dependencies]
tempfile = "3.10"
